services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: alura_agente_backend
    ports:
      - "8000:8000"
    volumes:
      - faiss_data:/app/faiss_index
      - uploaded_docs:/app/stored_docs
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - HOST=${HOST}
      - PORT=${PORT}
    restart: always

  frontend_web:
    env_file:
      - .env
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: alura_agente_frontend
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always

  nginx_proxy:
    image: nginx:1.27-alpine
    container_name: alura_agente_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend_web
      - backend

volumes:
  faiss_data:
  uploaded_docs:
  frontend_dist:
